### ISSUE TITLE
[1.18.2]unusual prehistory v1.1.0 's lang.

### ISSUE THREAD

**Issue by BL4CKLOTU5www** [Peeko32213/Unusual-Prehistory#16]
till the version is the newest, the lang have not "advancement"for it.
I just write down the zh_cn lang for mods, but it doesn't work.
maybe it's time to have a change for "date\unusualprehistory\advancement\**.json  "title:translate"&"description:translate" ?"
I sent an issue cause I'm not authorited to change the date(without permission?:P)
the mod is coooool that I am glad to provide zh_cn for it :D

**Comment by Scouter456** [comment]
the advancements can be translated next update

**Comment by Scouter456** [comment]
If youre still interested in making a translation let me know ^^
