### ISSUE TITLE
The source of the dino sound is in the player's head

### ISSUE THREAD

**Issue by BlackAures1** [Peeko32213/Unusual-Prehistory#71]
unusualprehistory-1.3.3

The sound is not played from the dino position, but directly from the player's position. This is very confusing.
To verify: being far away from the dino and close. There is no difference in sound volume.

**Comment by Scouter456** [comment]
Which dino are you talking about?

**Comment by BlackAures1** [comment]
It's definitely happening to the one with the helmet on his head (pachycephalosaurus?), but you should check everyone else as well.

**Comment by BlackAures1** [comment]
This problem occurs when the sound format is dual-channel.

**Comment by Scouter456** [comment]
Should be fixed in the next update
