### ISSUE TITLE
Lack of animation for swimming and wrong position

### ISSUE THREAD

**Issue by BlackAures1** [Peeko32213/Unusual-Prehistory#72]
![image](https://github.com/Peeko32213/Unusual-Prehistory/assets/43911230/5466ea05-5cfe-4e8e-8bb9-25210d107fd2)
![image](https://github.com/Peeko32213/Unusual-Prehistory/assets/43911230/5b51113f-e373-42ba-88d9-ec76a1663850)

**Comment by Scouter456** [comment]
Should be added in upcoming update
