### ISSUE TITLE
Slight optimization problems

### ISSUE THREAD

**Issue by BlackAures1** [Peeko32213/Unusual-Prehistory#73]
![image](https://github.com/Peeko32213/Unusual-Prehistory/assets/43911230/9459fc82-c71e-454d-9422-f4fff1685682)
https://spark.lucko.me/0KAnK6gp4N - Naturally generated dinos affect optimization.

**Comment by Scouter456** [comment]
Well, kentro should get a boost in performance, as for others I don't see any so I am not sure if you're referring to more.
