### ISSUE TITLE
Drop Spam

### ISSUE THREAD

**Issue by BlackAures1** [Peeko32213/Unusual-Prehistory#74]
![image](https://github.com/Peeko32213/Unusual-Prehistory/assets/43911230/cf3487b4-b44b-41db-9336-5e71ce909b2e)

When naturally spawned in the world, sea creatures hunt and litter the world with loot. Make a check to make sure the source of damage is the player, not everyone.

**Comment by Scouter456** [comment]
Dunk should be more passive now
