### ISSUE TITLE
New localization

### ISSUE THREAD

**Issue by BlackAures1** [Peeko32213/Unusual-Prehistory#82]
ru_ru - Russian Language - mod + encyclopedia - [ru_ru.zip](https://github.com/Peeko32213/Unusual-Prehistory/files/11518926/ru_ru.zip) (DOWNLOAD)
The names of the dinos have also been translated. Some of the descriptions in the encyclopedia have been slightly altered to make more accurate sense. It took many hours and I would be glad if any other Russian-speaking users would check it out with a fresher eye (because I am endlessly tired of checking names). The translation is fully ready for use.

![image](https://github.com/Peeko32213/Unusual-Prehistory/assets/43911230/f39f8e7d-66df-433e-8112-096a22507064)
![image](https://github.com/Peeko32213/Unusual-Prehistory/assets/43911230/73b45336-473a-42e7-89c4-1693eb9c9129)

**Comment by Scouter456** [comment]
Yes, thanks I only saw this now, if you want you can send them to me on discord

**Comment by BlackAures1** [comment]
I've sent this to you on discord, in private messages and even here, but you've ignored it several times.  Even in this message there is a direct link to download the translation.

**Comment by Scouter456** [comment]
Alright everything is added, thanks for your contribution!
