### ISSUE TITLE
Eternal shaking

### ISSUE THREAD

**Issue by BlackAures1** [Peeko32213/Unusual-Prehistory#85]
1.19.2 unusualprehistory-1.3.4.1
Very often there is a bug that leaves the camera shaking when you fly away from the bracha in creative mode.  Clearing the effects with the command does not work. The shake effect hangs on the player indefinitely from 00:00 time to the end. The only way to fix this is to approach the brachi again and slowly walk away from it.

**Comment by Scouter456** [comment]
I have seen this, don't know a fix for it at the moment, it can also be fixed by relogging

**Comment by BlackAures1** [comment]
Sometimes it is fixed by the longer duration of the effect

**Comment by Scouter456** [comment]
I think this should be fixed in the next update!
