### ISSUE TITLE
Hwachavenator Problems 

### ISSUE THREAD

**Issue by BlackAures1** [Peeko32213/Unusual-Prehistory#86]
1. Hwachavenator can break a player who tried to sit on it. The server continues to think that the player stayed in the same place where he sat on the Hwachavenator, but to the client the character will be very far away. At this point it is impossible to get off the Hwachavenator and the only way to fix the problem is to go to the menu.

2. Terrible visibility while controlling the Hwachavenator. Neither third-person nor first-person it's impossible to see where you're shooting. In one version you are looking under your tail, and in the second version you are looking at your head for 90% of the screen.

3. Player takes a huge amount of damage from falling even when ride Hwachavenator.

**Comment by Scouter456** [comment]
How do you produce the first one?

**Comment by BlackAures1** [comment]
I can't say for sure when it happens, but it has happened at least twice in different preservations and circumstances. If it happens again, I'll tell you more accurately with logs and other.
